/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as IntakeRouteRouteImport } from './routes/intake/route'
import { Route as CasesRouteRouteImport } from './routes/cases/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as IntakeIndexRouteImport } from './routes/intake/index'
import { Route as CasesIndexRouteImport } from './routes/cases/index'
import { Route as IntakeNewRouteImport } from './routes/intake/new'
import { Route as CasesCaseIdRouteImport } from './routes/cases/$caseId'

const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const IntakeRouteRoute = IntakeRouteRouteImport.update({
  id: '/intake',
  path: '/intake',
  getParentRoute: () => rootRouteImport,
} as any)
const CasesRouteRoute = CasesRouteRouteImport.update({
  id: '/cases',
  path: '/cases',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const IntakeIndexRoute = IntakeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => IntakeRouteRoute,
} as any)
const CasesIndexRoute = CasesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CasesRouteRoute,
} as any)
const IntakeNewRoute = IntakeNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => IntakeRouteRoute,
} as any)
const CasesCaseIdRoute = CasesCaseIdRouteImport.update({
  id: '/$caseId',
  path: '/$caseId',
  getParentRoute: () => CasesRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cases': typeof CasesRouteRouteWithChildren
  '/intake': typeof IntakeRouteRouteWithChildren
  '/reports': typeof ReportsRoute
  '/cases/$caseId': typeof CasesCaseIdRoute
  '/intake/new': typeof IntakeNewRoute
  '/cases/': typeof CasesIndexRoute
  '/intake/': typeof IntakeIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/reports': typeof ReportsRoute
  '/cases/$caseId': typeof CasesCaseIdRoute
  '/intake/new': typeof IntakeNewRoute
  '/cases': typeof CasesIndexRoute
  '/intake': typeof IntakeIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cases': typeof CasesRouteRouteWithChildren
  '/intake': typeof IntakeRouteRouteWithChildren
  '/reports': typeof ReportsRoute
  '/cases/$caseId': typeof CasesCaseIdRoute
  '/intake/new': typeof IntakeNewRoute
  '/cases/': typeof CasesIndexRoute
  '/intake/': typeof IntakeIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cases'
    | '/intake'
    | '/reports'
    | '/cases/$caseId'
    | '/intake/new'
    | '/cases/'
    | '/intake/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/reports' | '/cases/$caseId' | '/intake/new' | '/cases' | '/intake'
  id:
    | '__root__'
    | '/'
    | '/cases'
    | '/intake'
    | '/reports'
    | '/cases/$caseId'
    | '/intake/new'
    | '/cases/'
    | '/intake/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CasesRouteRoute: typeof CasesRouteRouteWithChildren
  IntakeRouteRoute: typeof IntakeRouteRouteWithChildren
  ReportsRoute: typeof ReportsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intake': {
      id: '/intake'
      path: '/intake'
      fullPath: '/intake'
      preLoaderRoute: typeof IntakeRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cases': {
      id: '/cases'
      path: '/cases'
      fullPath: '/cases'
      preLoaderRoute: typeof CasesRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intake/': {
      id: '/intake/'
      path: '/'
      fullPath: '/intake/'
      preLoaderRoute: typeof IntakeIndexRouteImport
      parentRoute: typeof IntakeRouteRoute
    }
    '/cases/': {
      id: '/cases/'
      path: '/'
      fullPath: '/cases/'
      preLoaderRoute: typeof CasesIndexRouteImport
      parentRoute: typeof CasesRouteRoute
    }
    '/intake/new': {
      id: '/intake/new'
      path: '/new'
      fullPath: '/intake/new'
      preLoaderRoute: typeof IntakeNewRouteImport
      parentRoute: typeof IntakeRouteRoute
    }
    '/cases/$caseId': {
      id: '/cases/$caseId'
      path: '/$caseId'
      fullPath: '/cases/$caseId'
      preLoaderRoute: typeof CasesCaseIdRouteImport
      parentRoute: typeof CasesRouteRoute
    }
  }
}

interface CasesRouteRouteChildren {
  CasesCaseIdRoute: typeof CasesCaseIdRoute
  CasesIndexRoute: typeof CasesIndexRoute
}

const CasesRouteRouteChildren: CasesRouteRouteChildren = {
  CasesCaseIdRoute: CasesCaseIdRoute,
  CasesIndexRoute: CasesIndexRoute,
}

const CasesRouteRouteWithChildren = CasesRouteRoute._addFileChildren(
  CasesRouteRouteChildren,
)

interface IntakeRouteRouteChildren {
  IntakeNewRoute: typeof IntakeNewRoute
  IntakeIndexRoute: typeof IntakeIndexRoute
}

const IntakeRouteRouteChildren: IntakeRouteRouteChildren = {
  IntakeNewRoute: IntakeNewRoute,
  IntakeIndexRoute: IntakeIndexRoute,
}

const IntakeRouteRouteWithChildren = IntakeRouteRoute._addFileChildren(
  IntakeRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CasesRouteRoute: CasesRouteRouteWithChildren,
  IntakeRouteRoute: IntakeRouteRouteWithChildren,
  ReportsRoute: ReportsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
